#pragma once

#include "Event/IEvent.h"

enum Key : int {
	KEY_ESCAPE, KEY_F1, KEY_F2, KEY_F3, KEY_F4, KEY_F5, KEY_F6, KEY_F7, KEY_F8, KEY_F9,
	KEY_F10, KEY_F11, KEY_F12,

	KEY_BACKTICK, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_0,
	KEY_MINUS, KEY_EQUAL, KEY_BACKSPACE,
	
	KEY_TAB, KEY_Q, KEY_W, KEY_E, KEY_R, KEY_T, KEY_Y, KEY_U, KEY_I, KEY_O, KEY_P,
	KEY_LEFT_BRACKET, KEY_RIGHT_BRACKET, KEY_BACKSLASH,

	KEY_CAPS_LOCK, KEY_A, KEY_S, KEY_D, KEY_F, KEY_G, KEY_H, KEY_J, KEY_K, KEY_L,
	KEY_SEMICOLON, KEY_APOSTROPHE, KEY_ENTER,

	KEY_LEFT_SHIFT, KEY_Z, KEY_X, KEY_C, KEY_V, KEY_B, KEY_N, KEY_M, KEY_COMMA,
	KEY_PERIOD, KEY_SLASH, KEY_RIGHT_SHIFT,

	KEY_LEFT_CTRL, KEY_LEFT_ALT, KEY_SPACE, KEY_RIGHT_ALT, KEY_FN,
	KEY_RIGHT_CTRL, KEY_LEFT, KEY_DOWN, KEY_UP, KEY_RIGHT,

	KEY_UNKNOWN = -1,
};

enum KeyAction : int {
	RELEASE, PRESS, REPEAT, UNKNOWN = -1
};

struct KeyPressEvent : IEvent {
	KeyPressEvent(Key key, KeyAction action) : key(key), action(action) {}
	Key key; 
	KeyAction action; 
};